#!/bin/bash
cfg=/boot/config/plugins/bridge/bridge.cfg

# No custom file?
[[ ! -f $cfg ]] && exit

# Read settings
source $cfg

# Setup bridge interface
[[ $SERVICE == enable ]] && /usr/local/emhttp/plugins/bridge/scripts/write_config.sh
