#!/bin/bash
#
# NUT NOTIFYCMD script macester macecapri@gmail.com
# 2017.05.02 modified by Derek Macias
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin
PROG="nut"
PLGPATH="/boot/config/plugins/$PROG"
CONFIG=$PLGPATH/$PROG.cfg
NOTIFY="/usr/local/emhttp/plugins/dynamix/scripts/notify"

# read our configuration
[ -e "$CONFIG" ] && source $CONFIG

trap "exit 0" SIGTERM
if [ "$NOTIFYTYPE" = "ONLINE" ]
then
        echo $0: power restored | wall
                $NOTIFY -e "UPS Notification" -s "UPS is no longer on battery" -i "normal"
        # Cause all instances of this script to exit.
        killall -s SIGTERM `basename $0`
fi
if [ "$NOTIFYTYPE" = "ONBATT" ]
then
        echo $0: $TIMEOUT seconds till system powers down... | wall
               $NOTIFY -e "UPS Notification" -s "UPS is on battery" -i "alert"
        # Loop with one second interval to allow SIGTERM reception.
        let "n = $TIMEOUT"
        while [ $n -ne 0 ]
        do
                sleep 1
                let "n--"
        done
        echo $0: commencing shutdown | wall
                $NOTIFY -e "UPS Notification" -s "UPS is shutting down unRAID" -i "alert"
        upsmon -c fsd
fi